/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c1c6d7",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#2f1400",
        "inverse-primary": "#adc7ff",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#001f27",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-container": "#a96428",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#adc7ff",
        "tertiary-fixed-dim": "#ffb780",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-surface-variant": "#414754",
        "secondary-fixed-dim": "#3cd7ff",
        "secondary-fixed": "#b4ebff",
        "primary-fixed": "#d8e2ff",
        "primary-container": "#0070ea",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline": "#717786",
        "tertiary": "#8b4c11",
        "on-primary-fixed": "#001a41",
        "on-secondary": "#ffffff",
        "surface-tint": "#005bc0",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcc4",
        "on-background": "#191c1e",
        "secondary": "#2563eb",
        "surface-container-lowest": "#ffffff",
        "primary": "#031033",
        "surface": "#f7f9fb",
        "on-primary-container": "#fefcff",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed-variant": "#004493",
        "secondary-container": "#00d2fd",
        "on-secondary-container": "#005669",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "xs": "4px",
        "container-max": "1280px",
        "sm": "12px",
        "base": "8px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
};
